CREATE DATABASE p_venta1;
USE p_venta1;


CREATE TABLE usuarios
(
    ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOMBRE TEXT,
    APELLIDO_P VARCHAR(20),
    APELLIDO_M VARCHAR(20),
    NICKNAME VARCHAR(20),
    PASSWORD INT
);


CREATE TABLE proveedores
(
  ID_PROVEEDOR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NOMBE TEXT,
  E_MAIL TEXT,
  TELEFONO DOUBLE
);


CREATE TABLE productos
(
  ID_PRODUCTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NOMBRE TEXT,
  EXISTENCIA INT,
  PRECIO_NETO INT,
  PRECIO_VENTA INT,
  ID_PROVEEDOR INT,

  FOREIGN KEY (ID_PROVEEDOR) REFERENCES proveedores(ID_PROVEEDOR)
);

CREATE TABLE categoria
(
  ID_CATEGORIA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(40),
  ID_PRODUCTO INT,

  FOREIGN KEY (ID_PRODUCTO) REFERENCES productos(ID_PRODUCTO)
);

CREATE TABLE ventas
(
  ID_VENTA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ID_USUARIO INT,
  ID_PRODUCTO INT,

  FOREIGN KEY (ID_USUARIO) REFERENCES usuarios(ID_USUARIO),
  FOREIGN KEY (ID_PRODUCTO) REFERENCES  productos(ID_PRODUCTO)
);



select * from usuarios;
show create table usuarios;
insert into usuarios values (1,'Luis Gerardo','Roman','Marin','luis5648',12345);

update usuarios 
set PASSWORD = '12345'
where NOMBRE = 'Luis Gerardo';


alter table usuarios change PASSWORD PASSWORD varchar(25);

